### ISSUE TITLE
FileNotFoundError while running app.py

### ISSUE THREAD

**Issue by debajyoti94** [maelfabien/NLP_Summer_School-2021_Speech_Demo#1]
Hello,
After executing `streamlit run app.py` i see this error on the browser: `FileNotFoundError: [Errno 2] No such file or directory: 'src/key.txt'`. Turns out `key.txt` does not exist in the `src/` directory.
Wanted to ensure if this is expected, as the tutorial is tomorrow.

Thanks!

**Comment by maelfabien** [comment]
Hey!
It's supposed to be your API key indeed, so that's why it's not there. Will add these instructions in the README.
Thanks
